on:
  push:
  schedule:
  - cron: '0 12 * * *'
concurrency: cron
defaults:
  run:
    shell: bash
jobs:
  cron:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to update state & gh-pages branch
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
    - uses: actions/checkout@v5
    - name: Set up worktrees
      run: |-
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git worktree add gh-pages gh-pages
        git worktree add state state
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # pin to 0.8.18, latest as of 2025/09/18
        version: "0.8.18"
    - name: Fetch RSS feeds and translate
      timeout-minutes: 10
      env:
        GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
      run: uv run xinwennl_rss.py
    - name: Commit if dirty
      run: |-
        git config --global user.name 'GitHub Actions'
        git config --global user.email "$(whoami)@$(hostname --fqdn)"
        dirty() {
        	[ -n "$(git status --porcelain)" ]
        }
        push() {
        	git add --all
        	git commit --amend --reset-author --message "${2:-automatic commit}"
        	git push --force
        }
        (cd gh-pages; if dirty; then push; echo "DEPLOY=1" >> "${GITHUB_ENV}"; fi)
        (cd state; if dirty; then push; fi)
    - uses: actions/configure-pages@v5
      if: env.DEPLOY == '1'
    - uses: actions/upload-pages-artifact@v4
      if: env.DEPLOY == '1'
      with:
        path: gh-pages
    - uses: actions/deploy-pages@v4
      if: env.DEPLOY == '1'
